### ISSUE TITLE
Close icon not showing

### ISSUE THREAD

**Issue by AlexanderBielen** [Hydrane/angular2-notification-bar#2]
I am using these versions of angular 2, material and cli:
@angular/core: 2.4.9
@angular/material: 2.0.0-beta.2
@angular/cli: 1.0.0-rc.1

For me the icon inside the close button is not showing, but the button is there. http://prntscr.com/ehgchp
Also is there a way to change the height of the notifications?

**Comment by jsrkstr** [comment]
Fixed  the issue with icon.
You can override css classes of notification, notification-wrapper, close-click, etc to give custom styling.
